[build]
  command = "npm run build"
  publish = ".output/public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[build.environment]
  NODE_VERSION = "20"

[functions]
  included_files = ["server/**"]